apiVersion: numaplane.numaproj.io/v1alpha1
kind: PipelineRollout
metadata:
  name: my-pipeline-slow
  namespace: example-namespace
spec:
  pipeline:
    spec:
      interStepBufferServiceName: my-isbsvc
      limits:
        readBatchSize: 1
      lifecycle:
        pauseGracePeriodSeconds: 200
      vertices:
        - name: in
          scale:
            min: 1
            max: 1
          source:
            generator:
              rpu: 100
              duration: 1s
          containerTemplate:
            env:
              - name: NUMAFLOW_DEBUG
                value: "true"
        - name: cat-2
          scale:
            min: 1
            max: 1
          udf:
            builtin:
              name: cat
          containerTemplate:
            env:
              - name: NUMAFLOW_DEBUG
                value: "true"
        - name: out
          sink:
            log: {}
          scale:
            min: 1
            max: 1
      edges:
        - from: in
          to: cat-2
        #- from: cat
        #  to: cat-2
        #- from: cat-2
        #  to: out
        - from: cat-2
          to: out
