apiVersion: numaplane.numaproj.io/v1alpha1
kind: ISBServiceRollout
metadata:
  name: my-isbsvc
  namespace: example-namespace
spec:
  interStepBufferService:
    spec:
      jetstream:
        version: 2.10.11
        persistence:
          volumeSize: 1Gi
