apiVersion: numaplane.numaproj.io/v1alpha1
kind: ISBServiceRollout
metadata:
  name: my-isbsvc
  namespace: example-namespace
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  interStepBufferService:
    spec:
      # Example from https://github.com/numaproj/numaflow/blob/main/examples/0-isbsvc-jetstream.yaml
      jetstream:
        version: 2.10.3
        persistence:
          volumeSize: 1Gi
        replicas: 5