apiVersion: numaplane.numaproj.io/v1alpha1
kind: MonoVertexRollout
metadata:
  name: my-monovertex
  namespace: example-namespace
spec:
  monoVertex:
    spec:
      source:
        udsource:
          container:
            image: quay.io/numaio/numaflow-go/source-simple-source:stable
      sink:
        udsink:
          container:
            image: quay.io/numaio/numaflow-go/sink-log:stable