apiVersion: numaplane.numaproj.io/v1alpha1
kind: MonoVertexRollout
metadata:
  name: my-monovertex
  namespace: example-namespace
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  monoVertex:
    spec:
      scale:
        min: 1
        max: 1
      source:
        udsource:
          container:
            image: quay.io/numaio/numaflow-java/source-simple-source:stable
        # transformer is an optional container to do any transformation to the incoming data before passing to the sink
        transformer:
          container:
            image: quay.io/numaio/numaflow-rs/source-transformer-now:stable
      sink:
        udsink:
          container:
            image: quay.io/numaio/numaflow-java/simple-sink:stable
