apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-setup
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/juliev0/ged24-demo.git
    targetRevision: HEAD
    path: resources/argocd-setup
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-setup
  # syncPolicy:
  #   automated:
  #     selfHeal: true
  #     prune: true
